apiVersion: v1
kind: Secret
metadata:
  name: wallet-demo-wallet
  labels:
    app: wallet-demo
    app.kubernetes.io/component: wallet
type: Opaque
stringData:
  oidc-client-secret: {{ .Values.wallet.clientSecret }}
  {{- if .Values.wallet.conformance.apiKey }}
  verifier-conformance-api-key: {{ .Values.wallet.conformance.apiKey }}
  {{- end }}
